# Generated by Django 6.0.4 on 2026-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_find', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
