# Generated by Django 6.0.4 on 2026-04-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_find', '0002_alter_userinfomodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_find.categorymodel'),
        ),
    ]
